# Generated by Django 2.1.7 on 2019-03-17 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20190317_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableplayer',
            name='player_type',
            field=models.BooleanField(default=False),
        ),
    ]
