# Generated by Django 2.1.7 on 2019-03-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_tableplayer_player_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='table_status',
            field=models.IntegerField(choices=[(0, 'inactive'), (1, 'active')], default=0),
        ),
        migrations.AlterField(
            model_name='tableplayer',
            name='player_type',
            field=models.IntegerField(choices=[(0, 'inactive'), (1, 'active')], default=0),
        ),
    ]
