# Generated by Django 2.1.7 on 2019-03-17 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0004_auto_20190317_0459'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_cards', models.CharField(max_length=256)),
                ('player_count', models.IntegerField(default=0)),
                ('player_status', models.IntegerField(choices=[(0, 'inactive'), (1, 'active')], default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'round_players',
            },
        ),
        migrations.AddField(
            model_name='round',
            name='dealer_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='round',
            name='round_status',
            field=models.IntegerField(choices=[(0, 'inactive'), (1, 'active')], default=0),
        ),
        migrations.AddField(
            model_name='roundplayer',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Round'),
        ),
    ]
