# Generated by Django 2.1.7 on 2019-03-17 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20190317_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.Table'),
            preserve_default=False,
        ),
    ]
