# Generated by Django 2.1.7 on 2019-03-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_round_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundplayer',
            name='player_bet',
            field=models.IntegerField(default=0),
        ),
    ]
