# Generated by Django 2.1.7 on 2019-03-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_roundplayer_player_bet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundplayer',
            name='player_bet',
            field=models.FloatField(default=0),
        ),
    ]
